import type { Metadata } from 'next';
import '@/app/globals.css';
import Providers from '@/app/providers';
import Header from '@/components/layout/Header';


export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <Providers>
            <Header />
            <div className="flex min-h-svh w-screen justify-center">
                <div className="w-full">{children}</div>
            </div>
        </Providers>
    );
}
