version: '3.8'

services:
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    command: npm run dev

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    env_file: .env
    depends_on:
      - db
    networks:
      - spring-boot-postgres-network
    ports:
      - "8080:8080"

  db:
    container_name: postgres-container
    image: postgres:14.1-alpine
    env_file: .env
    ports:
      - "5432:5432"
    networks:
      - spring-boot-postgres-network

volumes:
  db:

networks:
  spring-boot-postgres-network: