import type { Metadata } from 'next';
import '@/app/globals.css';
import Providers from '@/app/providers';

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <Providers>
            <div className="w-full">{children}</div>
        </Providers>
    );
}
